### ISSUE TITLE
付款方式 PayPal

### ISSUE THREAD

**Issue by demianrey** [ZBrettonYe/OtakuPanel_SSR#2]
您好，恭喜您對這個出色的面板進行了修改

您可以為不住在中國的人添加PayPal 付款方式，這對您有很大的幫助，如果您接受我願意捐款的話
問候

**Comment by ZBrettonYe** [comment]
如果可以的话，希望你能提供一下 对接案例，或者文档，方便我添加

**Comment by demianrey** [comment]
https://github.com/blcloud/SSRPanel/blob/master/app/Http/Controllers/PaymentController.php
Someone tried here some time ago, I installed it but when paying I did not send anything, but it is an idea of ​​how it is done, we must add the paypal sdk to the composer

**Comment by ZBrettonYe** [comment]
done
